name: Build Android APK

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
    - name: Checkout Code
      uses: actions/checkout@v4

    - name: Create buildozer.spec
      run: |
        cat <<EOF > buildozer.spec
        [app]
        title = ImageToPdf
        package.name = img2pdf
        package.domain = org.mohammad
        source.dir = .
        source.include_exts = py,png,jpg,jpeg
        version = 1.0
        requirements = python3,kivy==2.1.0,pillow,plyer
        orientation = portrait
        fullscreen = 0
        android.permissions = INTERNET,READ_EXTERNAL_STORAGE,WRITE_EXTERNAL_STORAGE
        android.api = 33
        android.minapi = 21
        android.accept_sdk_license = True
        [buildozer]
        log_level = 2
        warn_on_root = 1
        EOF

    - name: Build with Official Buildozer Action
      uses: ArtemSBulgakov/buildozer-action@v1
      id: buildozer
      with:
        command: buildozer android debug
        buildozer_version: master

    - name: Upload APK
      uses: actions/upload-artifact@v4
      with:
        name: Image-To-Pdf-App
        path: bin/*.apk
        
